GET http://localhost:4000

###

POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "firstName": "simone",
  "lastName": "taccarelli",
  "email": "simone.taccarelli.93@gmail.com",
  "password": "123456"
}


###

PUT http://localhost:4000/users/1
Content-Type: application/json

{
  "name": "John",
  "age": "31",
  "lastname": "Lennon"
}

###

DELETE http://localhost:4000/auth/67d5db4130db90f48df49ddd

###

//modify psw
###
